# Functions
## Practice Problems

### 1. Following the function design recipe, define:
  * a function that converts Fahrenheit into Celsius
  * a function that converts kilometers into miles. (Assume there are 1.6 kilometers in a mile.)

In [4]:
# Your code goes here
def fahrenheit_to_celsius(fahrenheit):
    celsisu = (fahrenheit - 32) *5 / 9
    return celsisu

fahrenheit = 98.6
fahrenheit_to_celsius(98.6)

37.0

In [7]:
def kilometers_to_miles (kilometers):
    miles = kilometers / 1.6
    return miles
kilometers_to_miles(40)

25.0

<details>
  <summary>Answer</summary>
  <pre>
    def fahrenheit_to_celsius(fahrenheit):
      celsius = (fahrenheit - 32) * 5 / 9
      return celsius
    temp_in_celsius = fahrenheit_to_celsius(98.6)
    print(temp_in_celsius)
  </pre>

</details>

### 2. What value is printed in the below code?

In [8]:
answer = 3

def answer_to_everything():
    '''Return the answer to life, the universe, and everything'''
    answer = 42
    return answer
    
answer_to_everything()

print(answer)

3

<details>
  <summary>Answer</summary>

  Answer: 3. The answer variable in our function is locally scoped -- our program cannot access the value 42 from outside of the function, including when we called print(answer).

  Although we called answer_to_everything(), we did not assign the output to a variable.
</details>

### 3. Complete the examples in the docstring below, then write the body of the function. You can assume `num` is always >= 0.

In [23]:
def repeat(string, num):
    ''' Return string repeated num times.
    >>> repeat('yes', 4)
    'yesyesyesyes'
    >>> repeat('no', 0) 
    # your expected output here
    ' '
    >>> repeat('yesnomaybe', 3)
    # your expected output here
    'yesnomaybeyesnomaybeyesnomaybe'
    '''
    output = string*num
    return output

repeat('no', 0)

''

In [11]:
repeat('happy', 5)

'happyhappyhappyhappyhappy'

<details>
  <summary>Answer</summary>
  <pre>
    from pickle import TRUE
    def repeat(string, num):
      ''' Return string repeated num times.
      >>> repeat('yes', 4)
      'yesyesyesyes'
      >>> repeat('no', 0)
      >>> repeat('yesnomaybe', 3)
      yesnomaybeyesnomaybeyesnomaybe
      '''
      output = string*num
      return output
  </pre>

</details>

### 4. Complete the function below. You can assume that `number` will always be a string with 10 digits and that the first 3 digits will always be the area code.

In [5]:
from pickle import TRUE
def is_416_number(number):
    ''' Check whether the number has a 416 area code.
    >>> is_416_number('(416)-555-5555')
    True
    >>> is_416_number('514 416 5555')
    False
    >>> is_416_number('4165554160')
    True
    '''
    # Your code goes here

In [34]:
def is_416_number(number):
    number = number.replace('(', '')
    number = number.replace(')', '')
    print(number)
    return number[:3] == '416'

In [38]:
is_416_number('(416)-555-5555')

416-555-5555

True

In [39]:
is_416_number('514 416 5555')

514 416 5555

False

<details>
  <summary>Answer</summary>
  <pre>
    from pickle import TRUE
    def is_416_number(number):
        ''' Check whether the number has a 416 area code.
        >>> is_416_number('(416)-555-5555')
        True
        >>> is_416_number('514 416 5555')
        False
        >>> is_416_number('4165554160')
        True
        '''
        # replace parens w/ nothing
        number = number.replace('(', '')
        number = number.replace(')', '')
        output = number[:3] == '416'
        return output
  </pre>

</details>